import NiiViewer from "./NiiViewer";
import { toViewerUrl } from "../data/patientCsv";

export default function ImagingPanel({
  patient,
  patientIndex,
  patientCount,
  onPreviousPatient,
  onNextPatient,
  isFirstPatient,
  isLastPatient,
}) {
  return (
    <section className="card imaging">
      <div className="card-header imaging-header">
        <div>
          <h2>Imaging Review</h2>
          <p>
            Patient {patient?.patient_id ?? "N/A"} ({Math.min(patientIndex + 1, patientCount)}/
            {patientCount}) · 3 modalities + classifier input.
          </p>
        </div>
        <div className="imaging-nav">
          <button
            type="button"
            className="ghost-btn"
            onClick={onPreviousPatient}
            disabled={isFirstPatient}
          >
            Previous Patient
          </button>
          <button type="button" className="ghost-btn" onClick={onNextPatient} disabled={isLastPatient}>
            Next Patient
          </button>
        </div>
      </div>
      {patient ? (
        <div className="image-grid four-up">
          <NiiViewer title="T2W" subtitle="Axial T2-weighted" url={toViewerUrl(patient.t2w)} />
          <NiiViewer title="ADC" subtitle="Diffusion-weighted ADC" url={toViewerUrl(patient.adc)} />
          <NiiViewer title="HBV" subtitle="High b-value" url={toViewerUrl(patient.hbv)} />
          {/*
            4th panel: exact MedSigLIP model input — HBV | ADC | HBV concatenated
            side-by-side, resampled to 0.3125×0.3125×3 mm, center-cropped to 448 px,
            1st-99th percentile normalised. Generated by scripts/generate_classifier_inputs.py.
          */}
          <NiiViewer
            title="INPUT"
            subtitle="MedSigLIP input · HBV | ADC | HBV · 448 px"
            url={toViewerUrl(patient.cls_input_nifti)}
          />
        </div>
      ) : (
        <div className="viewer-error">No patients found in CSV.</div>
      )}
    </section>
  );
}
